### ISSUE TITLE
Test py signal slot

### ISSUE THREAD

**Issue by rakeshkr-code** [rakeshkr-code/project-image_resizer#1]
import sys from PyQt5.QtCore import QObject, pyqtSignal, pyqtSlot from PyQt5.QtWidgets import QApplication class Worker(QObject): finished = pyqtSignal() @pyqtSlot() def do_work(self): # Simulate some work import time time.sleep(2) print("Work done") self.finished.emit() class Controller(QObject): def __init__(self): super().__init__() self.worker = Worker() self.worker_thread = None def start_work(self): # Create a thread for the worker from PyQt5.QtCore import QThread self.worker_thread = QThread() self.worker.moveToThread(self.worker_thread) self.worker_thread.started.connect(self.worker.do_work) self.worker.finished.connect(self.worker_thread.quit) self.worker.finished.connect(self.worker.deleteLater) self.worker_thread.finished.connect(self.worker_thread.deleteLater) self.worker_thread.start() if __name__ == "__main__": app = QApplication(sys.argv) controller = Controller() controller.start_work() sys.exit(app.exec_()) To address the issue of adding items to the scroll area from a subscriber callback in a different thread, you can use a signal-slot mechanism to communicate between threads. Here's how you can modify your code to achieve this: 1. Define a custom signal in your ROS node class that will be emitted when a message is received. 2. Connect this signal to a slot in your UI class that adds the item to the scroll area. 3. Emit the signal from the subscriber callback whenever a message is received.
Here's an example demonstrating this approach: ```python from PyQt5.QtCore import QObject, pyqtSignal from PyQt5.QtWidgets import QApplication, QVBoxLayout, QLabel, QWidget, QScrollArea import threading import rospy from std_msgs.msg import String class ROSNode(QObject): message_received = pyqtSignal(str) def __init__(self): super().__init__() rospy.init_node('ros_node') rospy.Subscriber('/some_topic', String, self.callback) def callback(self, msg): # Emit the message_received signal with the message data self.message_received.emit(msg.data) class MyUI(QWidget): def __init__(self): super().__init__() self.scroll_area = QScrollArea() self.scroll_content = QWidget() self.scroll_layout = QVBoxLayout(self.scroll_content) self.scroll_area.setWidgetResizable(True) self.scroll_area.setWidget(self.scroll_content) self.layout = QVBoxLayout(self) self.layout.addWidget(self.scroll_area) def add_item(self, text): label = QLabel(text) self.scroll_layout.addWidget(label) if __name__ == '__main__': app = QApplication([]) ros_node = ROSNode() # Create the UI ui = MyUI() ui.show() # Connect the ROS node's signal to the UI's slot ros_node.message_received.connect(ui.add_item) # Start the ROS node in a separate thread ros_thread = threading.Thread(target=rospy.spin) ros_thread.start()
sys.exit(app.exec_()) In this example:- `ROSNode` is a class representing your ROS node. It has a `message_received` signal that is emitted whenever a message is received on the `/some_topic` topic.- `MyUI` is a class representing your PyQt5 UI. It has a method `add_item` that adds a label to the scroll area.- Weconnect the `message_received` signal from the ROS node to the `add_item` slot in the UI class.- Whenamessageis received in the ROS callback, the `message_received` signal is emitted, triggering the `add_item` method in the UI class to add the item to the scroll area. This way, communication between the ROS node (running in a separate thread) and the UI is handled safely using signals and slots. The code I provided demonstrates this phenomenon through the use of signals and slots in PyQt5. Let me break down how this works: 1. **ROSNode Class**:- The `ROSNode` class is responsible for handling ROS-related functionalities.- It defines a `message_received` signal using `pyqtSignal(str)`. This signal will be emitted whenever a message is received on the `/some_topic` topic.- Inside the `callback` method, which is called when a message is received, the `message_received` signal is emitted with the message data (`msg.data`). 2. **MyUI Class**:- The `MyUI` class represents the PyQt5 GUI.- It defines a method `add_item` which takes text as input and adds a label containing that text to the scroll area.- The scroll area and its contents are set up in the `__init__` method of `MyUI`. 3. **Connection Between ROSNode and MyUI**:- After creating instances of `ROSNode` and `MyUI`, we connect the `message_received` signal from `ROSNode` to the `add_item` slot in `MyUI`.- This connection ensures that whenever a message is received in the ROS callback, the `add_item` method in the UI class will be triggered. 4. **Thread Setup**:- The ROS node (`ros_node`) is started in a separate thread using `threading.Thread(target=rospy.spin)`.- This ensures that ROS operations are performed in a separate thread, avoiding blocking the main GUI thread. 5. **Event Loop**:- Finally, we start the PyQt5 application event loop with `app.exec_()`, allowing both the ROS node and the PyQt5 GUI to run concurrently. So, when a message is received in the ROS callback, the `message_received` signal is emitted. This signal is connected to the `add_item` method in the UI class, which adds the received message to the scroll area. This communication between the ROS node and the UI is facilitated by the signal-slot mechanism provided by PyQt5.

**Comment by AngadManroy** [comment]
[pyslotsgnal.docx](https://github.com/rakeshkr-code/project-image_resizer/files/15005631/pyslotsgnal.docx)
